apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fluentd
spec:
  template:
    metadata:
      labels:
        service: fluentd
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - arm
      containers:
      - image: gganssauge/fluentd-arm
        imagePullPolicy: Always
        name: fluentd
        tty: true
        ports:
        - containerPort: 24224
        volumeMounts:
        - name: fluent-config-volume
          mountPath: /fluentd/etc/
      volumes:
      - name: fluent-config-volume
        configMap:
          name: fluent.conf
